services:
  backend:
    build:
      context: apps
    container_name: yabv-container
    environment:
      - FE_ORIGIN=http://165.22.52.220:8080
    image: yabv-be
    ports:
      - "8080:8080"
    networks:
      - nginx-net
    volumes:
      - ~/yabv/images:/app/images

networks:
  nginx-net:
    external: true
    name: nginx-default-network
