services:
  backend:
    build:
      context: ./apps/server
    container_name: yabv-be-container
    image: yabv-be
    ports:
      - "8080:8080"
    networks:
      - nginx-net

  frontend:
    build:
      context: ./apps/web
    container_name: yabv-fe-container
    image: yabv-fe
    ports:
      - "6969:6969"
    networks:
      - nginx-net

networks:
  nginx-net:
    external: true
    name: nginx-default-network
